"""Alembic environment for the self-hosted scan-result store.

Two properties matter more than anything else here, and both are tested in
tests/test_storage_migrations.py.

**1. This migration set owns only its own tables.**

The target database is not empty and will not be ours alone. The legacy
`models/__init__.py` schema (`clients`, `domains`, `projects`, `scans`,
`vulnerabilities`) may exist in it, and `ironcity-api` already has its own
schema on the same MariaDB instance — a Flask API that predates this product
and whose schema we have never seen (docs/HANDOFF.md §3.3 records that as
UNKNOWN).

Autogenerate compares the database against `target_metadata` and proposes a
DROP for every table it finds that the metadata does not describe. Pointed at a
shared database with no filter, the first autogenerated revision would propose
dropping another service's data. `include_object` restricts this environment to
the `ti_` prefix, so a table we do not own can neither be altered nor dropped by
a migration generated here.

**2. The connection string is never written down.**

`alembic.ini` carries no `sqlalchemy.url`. It comes from `DATABASE_URL`, the
same variable `config.py` already reads, and its absence is a loud failure
rather than a silent fallback to some default database.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

from threat_inspector.storage.schema import metadata

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = metadata

# Tables this migration set is allowed to create, alter or drop. Everything
# else in the database belongs to somebody else.
OWNED_PREFIX = "ti_"


def get_url() -> str:
    """The database to migrate. From the environment, never from a tracked file."""
    url = os.environ.get("DATABASE_URL", "").strip()
    if not url:
        raise RuntimeError(
            "DATABASE_URL is not set. Alembic will not guess a database to migrate — "
            "set it to the target DSN (e.g. mysql+pymysql://user:pass@host/db)."
        )
    return url


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Confine autogenerate and comparison to the tables this product owns.

    Without this, running autogenerate against the shared MariaDB instance would
    see every table belonging to ironcity-api and the legacy schema, conclude
    they are not in target_metadata, and propose dropping them.
    """
    if type_ == "table":
        return bool(str(name).startswith(OWNED_PREFIX))
    # An index or constraint is judged by the table it belongs to, so that a
    # legacy table's indexes are not proposed for removal either.
    parent = getattr(obj, "table", None)
    if parent is not None:
        return bool(str(parent.name).startswith(OWNED_PREFIX))
    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it.

    This is how a migration gets reviewed before it touches a database holding
    client findings: `alembic upgrade head --sql` prints exactly what would run.
    """
    context.configure(
        url=get_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        include_object=include_object,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section) or {}
    section["sqlalchemy.url"] = get_url()

    connectable = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
            # MariaDB DDL is not transactional, so a failed multi-statement
            # migration leaves the schema half-applied whatever we do here. Keep
            # each revision small enough to reason about on its own.
            render_as_batch=connection.dialect.name == "sqlite",
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
