name: Threat Inspector - Asset Discovery

# ============================================================
# ASSET DISCOVERY - Find subdomains and related assets
# Uses subfinder + httpx for comprehensive enumeration
# Triggered via CLI only - no manual runs without parameters
# ============================================================

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Root domain to enumerate (e.g., example.com)'
        required: true
      scan_id:
        description: 'Unique scan identifier from CLI'
        required: true
      client_id:
        description: 'Client identifier for reporting'
        required: false
        default: 'internal'

permissions:
  contents: read

concurrency:
  group: asset-discovery-${{ github.event.inputs.client_id }}
  cancel-in-progress: false

jobs:
  asset_discovery:
    name: Subdomain & Asset Discovery
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate inputs
        run: |
          if [ -z "${{ github.event.inputs.target }}" ]; then
            echo "❌ ERROR: target is required"
            exit 1
          fi
          if [ -z "${{ github.event.inputs.scan_id }}" ]; then
            echo "❌ ERROR: scan_id is required"
            exit 1
          fi
          
          # Clean domain
          TARGET="${{ github.event.inputs.target }}"
          TARGET=$(echo "$TARGET" | sed 's|https://||g' | sed 's|http://||g' | sed 's|/.*||g')
          echo "target_clean=$TARGET" >> $GITHUB_ENV
          
          echo "✅ Inputs validated"
          echo "🎯 Target: $TARGET"

      - name: Install Tools
        run: |
          # Install subfinder
          wget -q https://github.com/projectdiscovery/subfinder/releases/download/v2.6.3/subfinder_2.6.3_linux_amd64.zip
          unzip -q subfinder_2.6.3_linux_amd64.zip
          chmod +x subfinder
          sudo mv subfinder /usr/local/bin/
          
          # Install httpx
          wget -q https://github.com/projectdiscovery/httpx/releases/download/v1.3.7/httpx_1.3.7_linux_amd64.zip
          unzip -q httpx_1.3.7_linux_amd64.zip
          chmod +x httpx
          sudo mv httpx /usr/local/bin/
          
          # Verify
          subfinder -version
          httpx -version

      - name: Run Subfinder
        id: subfinder
        run: |
          TARGET="${{ env.target_clean }}"
          SCAN_ID="${{ github.event.inputs.scan_id }}"
          
          mkdir -p results
          
          echo "🔍 Starting subdomain enumeration for $TARGET"
          echo "================================================"
          
          # Run subfinder
          subfinder -d $TARGET -silent -o results/subdomains-${SCAN_ID}.txt
          
          # Count subdomains
          SUBDOMAIN_COUNT=$(wc -l < results/subdomains-${SCAN_ID}.txt || echo "0")
          
          echo "subdomain_count=$SUBDOMAIN_COUNT" >> $GITHUB_OUTPUT
          
          echo "================================================"
          echo "📊 Subdomains Found: $SUBDOMAIN_COUNT"
          
          # Show first 20
          echo "First 20 subdomains:"
          head -20 results/subdomains-${SCAN_ID}.txt

      - name: Run httpx Probe
        id: httpx
        run: |
          TARGET="${{ env.target_clean }}"
          SCAN_ID="${{ github.event.inputs.scan_id }}"
          
          echo "🔍 Probing live hosts with httpx"
          echo "================================================"
          
          # Probe subdomains
          cat results/subdomains-${SCAN_ID}.txt | httpx -silent -status-code -title -tech-detect -o results/live-hosts-${SCAN_ID}.txt
          
          # Count live hosts
          LIVE_COUNT=$(wc -l < results/live-hosts-${SCAN_ID}.txt || echo "0")
          
          echo "live_count=$LIVE_COUNT" >> $GITHUB_OUTPUT
          
          echo "================================================"
          echo "📊 Live Hosts: $LIVE_COUNT"
          
          # Show all live hosts
          echo "Live hosts:"
          cat results/live-hosts-${SCAN_ID}.txt

      - name: Generate JSON Output
        run: |
          SCAN_ID="${{ github.event.inputs.scan_id }}"
          
          # Create JSON output
          python3 << 'PYEOF'
          import json
          
          scan_id = "${{ github.event.inputs.scan_id }}"
          
          # Read subdomains
          subdomains = []
          try:
              with open(f"results/subdomains-{scan_id}.txt", "r") as f:
                  subdomains = [line.strip() for line in f if line.strip()]
          except:
              pass
          
          # Read live hosts
          live_hosts = []
          try:
              with open(f"results/live-hosts-{scan_id}.txt", "r") as f:
                  for line in f:
                      parts = line.strip().split()
                      if parts:
                          live_hosts.append({
                              "url": parts[0],
                              "status": parts[1] if len(parts) > 1 else "",
                              "title": " ".join(parts[2:]) if len(parts) > 2 else ""
                          })
          except:
              pass
          
          output = {
              "subdomains": subdomains,
              "live_hosts": live_hosts,
              "subdomain_count": len(subdomains),
              "live_count": len(live_hosts)
          }
          
          with open(f"results/assets-{scan_id}.json", "w") as f:
              json.dump(output, f, indent=2)
          
          print(json.dumps(output, indent=2))
          PYEOF

      - name: Generate Summary
        run: |
          SCAN_ID="${{ github.event.inputs.scan_id }}"
          
          cat << EOF > results/summary-${SCAN_ID}.md
          # Threat Inspector - Asset Discovery Results
          
          **Target:** ${{ env.target_clean }}
          **Scan ID:** ${{ github.event.inputs.scan_id }}
          **Client:** ${{ github.event.inputs.client_id }}
          **Timestamp:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          ## Summary
          
          | Metric | Value |
          |--------|-------|
          | **Subdomains Found** | ${{ steps.subfinder.outputs.subdomain_count }} |
          | **Live Hosts** | ${{ steps.httpx.outputs.live_count }} |
          
          ## Live Hosts
          
          \`\`\`
          $(cat results/live-hosts-${SCAN_ID}.txt)
          \`\`\`
          
          EOF
          
          cat results/summary-${SCAN_ID}.md

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asset-discovery-results-${{ github.event.inputs.scan_id }}
          path: results/
          retention-days: 90

      - name: Post to Firebase
        if: always()
        run: |
          curl -X POST "${{ secrets.FIREBASE_FUNCTION_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "scan_type": "asset_discovery",
              "scan_id": "${{ github.event.inputs.scan_id }}",
              "client_id": "${{ github.event.inputs.client_id }}",
              "target": "${{ env.target_clean }}",
              "subdomain_count": ${{ steps.subfinder.outputs.subdomain_count }},
              "live_count": ${{ steps.httpx.outputs.live_count }},
              "status": "completed",
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }' || echo "⚠️ Firebase post failed (function may not be deployed)"

      - name: Scan Complete
        run: |
          echo "================================================"
          echo "🛡️ THREAT INSPECTOR - ASSET DISCOVERY COMPLETE"
          echo "================================================"
          echo "Target: ${{ env.target_clean }}"
          echo "Subdomains: ${{ steps.subfinder.outputs.subdomain_count }}"
          echo "Live Hosts: ${{ steps.httpx.outputs.live_count }}"
          echo "Scan ID: ${{ github.event.inputs.scan_id }}"
          echo "================================================"
