name: Threat Inspector - Port Scan (Nmap)

# ============================================================
# NMAP PORT SCAN - Discover open ports and services
# Blue Team defensive reconnaissance
# Triggered via CLI only - no manual runs without parameters
# ============================================================

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target IP or hostname to scan'
        required: true
      scan_id:
        description: 'Unique scan identifier from CLI'
        required: true
      client_id:
        description: 'Client identifier for reporting'
        required: false
        default: 'internal'
      scan_type:
        description: 'Scan type: quick, standard, or full'
        required: false
        default: 'standard'

permissions:
  contents: read

concurrency:
  group: nmap-${{ github.event.inputs.client_id }}
  cancel-in-progress: false

jobs:
  port_scan:
    name: Nmap Port Scan
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate inputs
        run: |
          if [ -z "${{ github.event.inputs.target }}" ]; then
            echo "❌ ERROR: target is required"
            exit 1
          fi
          if [ -z "${{ github.event.inputs.scan_id }}" ]; then
            echo "❌ ERROR: scan_id is required"
            exit 1
          fi
          echo "✅ Inputs validated"
          echo "🎯 Target: ${{ github.event.inputs.target }}"
          echo "🔖 Scan ID: ${{ github.event.inputs.scan_id }}"
          echo "👤 Client: ${{ github.event.inputs.client_id }}"

      - name: Install Nmap
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap

      - name: Run Nmap Scan
        id: nmap
        run: |
          TARGET="${{ github.event.inputs.target }}"
          SCAN_TYPE="${{ github.event.inputs.scan_type }}"
          SCAN_ID="${{ github.event.inputs.scan_id }}"
          
          mkdir -p results
          
          echo "🔍 Starting $SCAN_TYPE Nmap scan on $TARGET"
          echo "================================================"
          
          case $SCAN_TYPE in
            quick)
              # Quick scan - top 100 ports
              nmap -T4 -F --top-ports 100 -oX results/nmap-${SCAN_ID}.xml -oN results/nmap-${SCAN_ID}.txt $TARGET
              ;;
            full)
              # Full scan - all ports with version detection
              nmap -T4 -p- -sV -sC -oX results/nmap-${SCAN_ID}.xml -oN results/nmap-${SCAN_ID}.txt $TARGET
              ;;
            *)
              # Standard scan - top 1000 ports with version detection
              nmap -T4 -sV -sC --top-ports 1000 -oX results/nmap-${SCAN_ID}.xml -oN results/nmap-${SCAN_ID}.txt $TARGET
              ;;
          esac
          
          echo "================================================"
          echo "✅ Nmap scan complete"

      - name: Parse Results
        id: parse
        run: |
          # Count open ports
          OPEN_PORTS=$(grep -c "open" results/nmap-${{ github.event.inputs.scan_id }}.txt || echo "0")
          
          # Extract port list
          PORTS=$(grep "open" results/nmap-${{ github.event.inputs.scan_id }}.txt | awk '{print $1}' | tr '\n' ',' | sed 's/,$//')
          
          echo "open_ports=$OPEN_PORTS" >> $GITHUB_OUTPUT
          echo "ports_list=$PORTS" >> $GITHUB_OUTPUT
          
          echo "📊 Open Ports Found: $OPEN_PORTS"
          echo "📋 Ports: $PORTS"

      - name: Generate Summary
        run: |
          cat << 'EOF' > results/summary-${{ github.event.inputs.scan_id }}.md
          # Threat Inspector - Port Scan Results
          
          **Target:** ${{ github.event.inputs.target }}
          **Scan ID:** ${{ github.event.inputs.scan_id }}
          **Client:** ${{ github.event.inputs.client_id }}
          **Scan Type:** ${{ github.event.inputs.scan_type }}
          **Timestamp:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
          
          ## Summary
          
          - **Open Ports Found:** ${{ steps.parse.outputs.open_ports }}
          - **Ports:** ${{ steps.parse.outputs.ports_list }}
          
          ## Full Results
          
          See attached artifacts for complete Nmap output.
          EOF
          
          cat results/summary-${{ github.event.inputs.scan_id }}.md

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nmap-results-${{ github.event.inputs.scan_id }}
          path: results/
          retention-days: 90

      - name: Post to Firebase
        if: always()
        run: |
          curl -X POST "${{ secrets.FIREBASE_FUNCTION_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "scan_type": "nmap",
              "scan_id": "${{ github.event.inputs.scan_id }}",
              "client_id": "${{ github.event.inputs.client_id }}",
              "target": "${{ github.event.inputs.target }}",
              "open_ports": ${{ steps.parse.outputs.open_ports }},
              "ports_list": "${{ steps.parse.outputs.ports_list }}",
              "status": "completed",
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }' || echo "⚠️ Firebase post failed (function may not be deployed)"

      - name: Scan Complete
        run: |
          echo "================================================"
          echo "🛡️ THREAT INSPECTOR - PORT SCAN COMPLETE"
          echo "================================================"
          echo "Target: ${{ github.event.inputs.target }}"
          echo "Open Ports: ${{ steps.parse.outputs.open_ports }}"
          echo "Scan ID: ${{ github.event.inputs.scan_id }}"
          echo "================================================"
